export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_PUESTOS = "GET_PUESTOS";
export const GET_ERRORS = "GET_ERRORS";
export const GET_CATEGORIAS = "GET_CATEGORIAS";
export const ADD_PUESTO = "ADD_PUESTO";
export const SAVE_TABLE = "SAVE_TABLE";
export const SHOW_MODAL = "SHOW_MODAL";
//ROWS 
export const ADD_CATEGORY_ROW = "ADD_CATEGORY_ROW";
export const ADD_ACTIVITY_ROW = "ADD_ACTIVITY_ROW";
export const DELETE_ROW = "DELETE_ROW";
export const ADD_EXTRA_ROW = "ADD_EXTRA_ROW";
export const UPDATE_ROW = "UPDATE_ROW";
export const UPDATE_ROW_INPUT = "UPDATE_ROW_INPUT";
export const UPDATE_ROW_INPUT_CAT = "UPDATE_ROW_INPUT_CAT"

//Display Checklist
export const GET_CHECKLIST = "GET_CHECKLIST";
export const GET_ERRORS_DISPLAY = "GET_ERRORS_DISPLAY";
export const GET_PUESTOS_DISPLAY = "GET_PUESTOS_DISPLAY";
export const ADD_PUESTO_DISPLAY = "ADD_PUESTO_DISPLAY";
export const SET_CURRENT_USER_DISPLAY = 'SET_CURRENT_USER_DISPLAY';
export const SET_ROWS = "SET_ROWS";
export const UPDATE_ROW_INPUT_DISPLAY = "UPDATE_ROW_INPUT_DISPLAY"
export const UPDATE_ROW_DISPLAY = "UPDATE_ROW_DISPLAY"
export const SAVE_TABLE_DISPLAY = "SAVE_TABLE_DISPLAY"

// Display answers
export const GET_PUESTOS_RESULTS = "GET_PUESTOS_RESULTS";
export const GET_ERRORS_RESULTS = "GET_ERRORS_RESULTS";


//PNC Chacklist
 //Levels
export const GET_LEVELS = 'GET_LEVELS';
export const GET_ERRORS_PNC = 'GET_ERRORS_PNC';
export const SET_SELECT = "SET_SELECT";
export const SET_QS= "SET_QS";
export const UPDATE_ROW_PNC = "UPDATE_ROW_PNC";
export const SAVE_TABLE_PNC = "SAVE_TABLE_PNC";
export const GET_CHECKLIST_PNC = "GET_CHECKLIST_PNC";
export const SET_ROWS_PNC = "SET_ROWS_PNC";
export const UPDATE_ROW_INPUT_PNC = "UPDATE_ROW_INPUT_PNC"
export const UPDATE_RESP_PNC = "UPDATE_RESP_PNC"
export const  SAVE_ANSWER_PNC = "SAVE_ANSWER_PNC"
